packages:
  - 'packages/*'
  - 'packages/nui/*'
  - 'packages/nuicss/*'
  - 'packages/utils/*'
  - 'packages/locale/*'
  - 'examples/nuicss/*'
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'nx'
  - 'sharp'
