/**
 * @license
 * Copyright (C) 2025 Nofinite
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Import your source directly
import { countries } from '../src/data/countries';

// Setup paths
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// This targets: src/styles/_countries.scss
const targetPath = path.join(__dirname, '../src/styles/_countries.scss');

async function generate() {
  console.log('Generating SCSS country list...');

  // Extract and normalize codes (lowercase, e.g., 'us', 'in')
  const codes = countries
    .map((c) => c.iso2.toLowerCase())
    .sort(); // Sort alphabetically for neatness

  // Create the SCSS content
  const fileContent = `/**
 * @license
 * Copyright (C) 2025 Nofinite
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
 /* ----------------------------------------------
  AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
  Source: src/data/countries.ts
  Generated by: scripts/generate-styles.ts
  ------------------------------------------------*/

$list: (
  ${codes.map((code) => `"${code}"`).join(',\n  ')}
);
`;

  // Write to file
  try {
    fs.writeFileSync(targetPath, fileContent, 'utf-8');
    console.log(`✅ Successfully generated styles for ${codes.length} countries.`);
    console.log(`📍 Output: ${targetPath}`);
  } catch (error) {
    console.error('❌ Error writing SCSS file:', error);
    process.exit(1);
  }
}

generate();