import type { NuicssConfig } from '@nofinite/nuicss';
import { presetUno, presetWind } from 'unocss';

export function nuiPreset(): NuicssConfig {
  return {
    presets: [
      presetUno(),
      presetWind(),
    ],
    shortcuts: {
      'bg-page': 'bg-[color:var(--bg-page)]',
      'bg-surface': 'bg-[color:var(--bg-surface)]',
      'bg-surface-raised': 'bg-[color:var(--bg-surface-raised)]',
      'bg-surface-overlay': 'bg-[color:var(--bg-surface-overlay)]',
      'bg-subtle': 'bg-[color:var(--bg-subtle)]',
      'bg-muted': 'bg-[color:var(--bg-muted)]',
      'bg-accent': 'bg-[color:var(--bg-accent)]',
      'bg-overlay': 'bg-[color:var(--bg-overlay)]',
      'bg-glass': 'bg-[color:var(--glass-bg)]',
      'text-default': 'text-[color:var(--fg-default)]',
      'text-subtle': 'text-[color:var(--fg-subtle)]',
      'text-muted': 'text-[color:var(--fg-muted)]',
      'text-accent': 'text-[color:var(--fg-accent)]',
      'text-inverse': 'text-[color:var(--fg-inverse)]',
      'text-disabled': 'text-[color:var(--fg-disabled)]',
      'border-default': '[border-color:var(--border-default)]',
      'border-strong': '[border-color:var(--border-strong)]',
      'border-subtle': '[border-color:var(--border-subtle)]',
      'border-hover': '[border-color:var(--border-hover)]',
      'border-focus': '[border-color:var(--border-focus)]',
      'border-disabled': '[border-color:var(--border-disabled)]',
      'border-glassBorder': '[border-color:var(--glass-border)]',
      'ring-focus': 'ring-[color:var(--focus-ring)]',
      'ring-offset-surface': 'ring-offset-[color:var(--bg-surface)]',
      'ring-offset-background': 'ring-offset-[color:var(--bg-page)]',
    },
    content: {
      pipeline: {
        include: [
          /.*\/node_modules\/@nofinite\/nui\/.*\.js$/,
          /.*\/node_modules\/@nofinite\/nui\/.*\.cjs$/,
          /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
          'src/**/*.{js,ts,jsx,tsx}',
        ],
      },
    },
    theme: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-active': 'var(--color-primary-active)',
        'primary-fg': 'var(--color-primary-fg)',
        'primary-subtle': 'var(--color-primary-subtle)',
        danger: 'var(--color-danger)',
        'danger-subtle': 'var(--color-danger-subtle)',
        'danger-fg': 'var(--color-danger-fg)',
        success: 'var(--color-success)',
        'success-subtle': 'var(--color-success-subtle)',
        'success-fg': 'var(--color-success-fg)',
        warning: 'var(--color-warning)',
        'warning-subtle': 'var(--color-warning-subtle)',
        'warning-fg': 'var(--color-warning-fg)',
        info: 'var(--color-info)',
        'info-subtle': 'var(--color-info-subtle)',
        'info-fg': 'var(--color-info-fg)',
        accent: 'var(--bg-accent)',
        'accent-fg': 'var(--fg-accent)',
      },
      spacing: {
        0: 'var(--space-0)',
        0.5: 'var(--space-0-5)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1-5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2-5)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        40: 'var(--space-40)',
        48: 'var(--space-48)',
        64: 'var(--space-64)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        none: 'var(--shadow-none)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        serif: 'var(--font-serif)',
        mono: 'var(--font-mono)',
      },
      animation: {
        keyframes: {
          'fade-in': '{ from { opacity: 0; } to { opacity: 1; } }',
          'fade-out': '{ from { opacity: 1; } to { opacity: 0; } }',
          'zoom-in': '{ from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }',
          'zoom-out': '{ from { opacity: 1; transform: scale(1); } to { opacity: 0; transform: scale(0.95); } }',
          'slide-in-up': '{ from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }',
          'slide-in-down': '{ from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }',
          'slide-out-up': '{ from { opacity: 1; transform: translateY(0); } to { opacity: 0; transform: translateY(-10px); } }',
          'slide-out-down': '{ from { opacity: 1; transform: translateY(0); } to { opacity: 0; transform: translateY(10px); } }',
        },
        durations: {
          'fade-in': '200ms',
          'fade-out': '150ms',
          'zoom-in': '200ms',
          'zoom-out': '150ms',
          'slide-in-up': '200ms',
          'slide-in-down': '200ms',
          'slide-out-up': '150ms',
          'slide-out-down': '150ms',
        },
        timingFns: {
          'fade-in': 'cubic-bezier(0.4, 0, 0.2, 1)',
          'fade-out': 'cubic-bezier(0.4, 0, 1, 1)',
          'zoom-in': 'cubic-bezier(0.4, 0, 0.2, 1)',
          'zoom-out': 'cubic-bezier(0.4, 0, 1, 1)',
          'slide-in-up': 'cubic-bezier(0.4, 0, 0.2, 1)',
          'slide-in-down': 'cubic-bezier(0.4, 0, 0.2, 1)',
          'slide-out-up': 'cubic-bezier(0.4, 0, 1, 1)',
          'slide-out-down': 'cubic-bezier(0.4, 0, 1, 1)',
        }
      }
    }
  };
}
