name: CI/CD

on:
  workflow_dispatch:
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v5

      - name: Run Tests
        run: pnpm nx affected -t test --exclude nui,nuicss-react-app

      - name: Build Packages
        run: pnpm nx affected -t build --exclude nui,nuicss-react-app

  publish:
    name: Publish Packages
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v5

      - name: Build Packages
        run: pnpm nx affected -t build --exclude nui,nuicss-react-app

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v2
        with:
          publish-script: pnpm changeset publish
          version-script: pnpm changeset version
          commit-message: "chore(release): version packages"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
